### ISSUE TITLE
Write up paper in Rmd

### ISSUE THREAD

**Issue by RobertASmithBresMed** [RobertASmithBresMed/plumberHE#16]

**Comment by RobertASmith** [comment]
[academicpaper.pdf](https://github.com/RobertASmithBresMed/plumberHE/files/8645184/academicpaper.pdf)

**Comment by RobertASmithBresMed** [comment]
I'm struggling to find a way to make the code chunk text smaller in the Rmd file : https://github.com/RobertASmithBresMed/plumberHE/blob/main/report/academicpaper.Rmd 

If either of you knows a way let me know.

I've tried:

::: {.tiny}

#| eval = F, echo = T, 
#| attr.source='.numberLines'
#* Echo back the input
#* @param msg The message to echo
#* @get /echo
function(msg="") {
  list(msg = paste0("The message is: '", msg, "'"))
}

::: 

```

**Comment by RobertASmith** [comment]
Solved - I've used \scriptsize and \normalsize.

**Comment by RobertASmith** [comment]
[academicpaper.pdf](https://github.com/RobertASmithBresMed/plumberHE/files/8645547/academicpaper.pdf)

**Comment by RobertASmith** [comment]
@RobertASmith I need to include reference to the usefulness of APIs for linking analysis done in different programming languages

**Comment by RobertASmithBresMed** [comment]
WHAT IS AN APPLICATION PROGRAMMING INTERFACE?
An API is an interface that allows unrelated software programs to communicate with one another. They act as bridges between two applications, allowing data to flow regardless of how each application was originally designed.  

For applications that function by pulling a constant stream of data from one or more sources, an API is especially important to decrease development time, save storage space on endpoint devices, and overcome any differences in the standards or programming languages used to create the data that lives at either end of the bridge.  

For example, third-party travel planning sites like Expedia or Kayak don’t generate data on their own to deliver comparisons of flight prices from ten or twelve different airlines.  

They simply use the API provided by each individual airline to plug into the flight scheduling software for each company and pull information into a single view for the end-user.

**Comment by RobertASmithBresMed** [comment]
Well-managed healthcare API exchanges usually include authentication, authorization, encryption, and signatures to ensure secure connections.  

[Authentication](http://healthitsecurity.com/news/controlling-healthcare-authentication-and-authorizations) and authorization are used to reliably determine a user’s identity and what resources they can access, usually through usernames and passwords. Security software certificates and hardware keys may also be used for extra security.

[Encryption](http://hitinfrastructure.com/news/health-data-encryption-grows-with-technology-advancements) hides data from unauthorized users and acts as a failsafe in the event the clinical data is stolen. Signatures are also used to validate API requests and ensure the data did not experience interference during transit.

The API Task Force report touches on APIs and HIPAA regulations, particularly focusing on patient-directed API technology. While managed APIs are secure, the risk factor rises when patients are accessing PHI without being familiar with the HIPAA Notice of Privacy Practices for Protected Health Information.

**Comment by RobertASmithBresMed** [comment]
Barton, G.R., Briggs, A.H. and Fenwick, E.A., 2008. Optimal cost‐effectiveness decisions: the role of the cost‐effectiveness acceptability curve (CEAC), the cost‐effectiveness acceptability frontier (CEAF), and the expected value of perfection information (EVPI). Value in health, 11(5), pp.886-897.

**Comment by RobertASmithBresMed** [comment]
Pouwels, X.G., Sampson, C.J., Arnold, R.J., Janodia, M.D., Henderson, R., Lamotte, M., Cowell, W., Borrill, J., Huttin, C., Udupa, N. and Gong, C.L., 2022. Opportunities and Barriers to the Development and Use of Open Source Health Economic Models: A Survey. Value in Health, 25(4), pp.473-479.
